# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: |
            (?x)(
                ^hdf5-blosc/|
                ^hdf5-blosc2/|
                ^ci/
            )
    -   id: end-of-file-fixer
        exclude: |
            (?x)(
                ^hdf5-blosc/|
                ^hdf5-blosc2/|
                ^ci/
            )
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
    -   id: mixed-line-ending
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: requirements-txt-fixer
        files: requirements.*\.in$

# -   repo: https://github.com/astral-sh/ruff-pre-commit
#     rev: v0.7.0
#     hooks:
#     -   id: ruff
#         args: [ --fix ]
#     -   id: ruff-format

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    -   id: pyupgrade
        args: [--py311-plus]

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        exclude: |
            (?x)(
                ^hdf5-blosc/|
                ^hdf5-blosc2/|
                ^ci/
            )

# -   repo: https://github.com/pycqa/pydocstyle
#     rev: 6.3.0
#     hooks:
#     -   id: pydocstyle

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)
        exclude: |
            (?x)(
                ^c-blosc/|
                ^hdf5-blosc/|
                ^hdf5-blosc2/
            )

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
    -   id: black
        language_version: python3.11
        exclude: |
            (?x)(
                ^c-blosc/|
                ^hdf5-blosc/|
                ^hdf5-blosc2/
            )

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.12.0
#     hooks:
#     -   id: mypy

# -   repo: https://github.com/codespell-project/codespell
#     rev: v2.2.4
#     hooks:
#     -   id: codespell
#         additional_dependencies: [tomli]
