version: 2

submodules:
  include: all

build:
  os: "ubuntu-20.04"
  tools:
    python: "3"
  apt_packages:
    - libblosc-dev
    - libbz2-dev
    - libhdf5-dev
    - liblz4-dev
    - liblzo2-dev
    - libsnappy-dev
    - libzstd-dev
    - zlib1g-dev

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
