name: PyTables
dependencies:
  - setuptools
  - pip
  - wheel
  - build
  - packaging
  - numpy
  - cython
  - bzip2
  - hdf5
  - lzo
  - blosc
  - blosc2
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
  - ipython
