.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH NCTOH5 1 "November 11, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
nctoh5 \- Convert a NetCDF file into a PyTables (HDF5 format) file
.SH SYNOPSIS
.B nctoh5
.RB \-h
.RB \-v
.RB \-o
.RB \-\-complevel=(0\-9)
.RB \-\-complib=lib
.RB \-\-shuffle=(0|1)
.RB \-\-fletcher32=(0|1)
.RB \-\-unpackshort=(0|1)
.RB \-\-quantize=(0|1)
.RB netcdffilename
.RB hdf5filename
.br
.SH DESCRIPTION
Convert a generic NetCDF file into a PyTables (HDF5 format) file
.SH OPTIONS
A summary of options is included below.
.TP
.B \-h
Prints a help text.
.TP
.B \-v
Show more information.
.TP
.B \-o
Overwite destination file.
.TP
.BI \-\-complevel=(0-9)
Sets a compression level (0 for no compression, which is the default).
.TP
.BI \-\-complib=lib
Sets the compression library to be used during the copy. \fIlib\fR can
be set to "zlib", "lzo" or "ucl". Defaults to "zlib".
.TP
.BI \-\-shuffle=(0|1)
Activate or not the shuffling filter (default is active if complevel>0).
.TP
.BI \-\-fletcher32=(0|1)
Whether activate or not the fletcher32 filter (not active by default).
.TP
.BI \-\-unpackshort=(0|1)
Unpack short integer variables to float variables using scale_factor
and add_offset netCDF variable attributes (not active by default).
.TP
.BI \-\-quantize=(0|1)
Quantize data to improve compression using least_significant_digit
netCDF variable attribute (not active by default).  See
.br
.nh
http://www.cdc.noaa.gov/cdc/conventions/cdc_netcdf_standard.shtml
.br
.hy
for further explanation of what this attribute means.

.br

.SH SEE ALSO
.BR ptdump (1), ptrepack (1).
.br
These utilities are documented fully by
.IR "PyTables user's manual".
.SH AUTHOR
This manual page was written by Francesc Altet <faltet@carabos.com>.
