import pickle as _pickle
import warnings
from pickle import DEFAULT_PROTOCOL, HIGHEST_PROTOCOL

from .exceptions import PickleNotAllowedError, PickleSecurityWarning

__all__ = [
    "DEFAULT_PROTOCOL",
    "HIGHEST_PROTOCOL",
    "dumps",
    "loads",
]


def dumps(obj, protocol=None, *, fix_imports=True, buffer_callback=None):
    """Return the pickled representation of the object as a bytes object.

    The optional *protocol* argument selects the pickle protocol.  If it is
    omitted, the interpreter's default protocol is used.

    Specifying a negative protocol version selects the highest protocol
    version supported.  The higher the protocol used, the more recent the
    version of Python needed to read the pickle produced.

    If *fix_imports* is True and *protocol* is less than 3, pickle will
    try to map the new Python 3 names to the old module names used in
    Python 2, so that the pickle data stream is readable with Python 2.

    If *buffer_callback* is None (the default), buffer views are serialized
    into *file* as part of the pickle stream.  It is an error if
    *buffer_callback* is not None and *protocol* is None or smaller than 5.
    """
    warnings.warn(
        "serializing objects with pickle creates data that requires "
        "unpickling to read; only unpickle data from trusted sources",
        PickleSecurityWarning,
        stacklevel=2,
    )
    return _pickle.dumps(
        obj, protocol, fix_imports=fix_imports, buffer_callback=buffer_callback
    )


def loads(
    data,
    /,
    *,
    fix_imports=True,
    encoding="ASCII",
    errors="strict",
    buffers=None,
    allow_pickle=False,
):
    """Read and return an object from the given pickle data.

    The protocol version of the pickle is detected automatically, so no
    protocol argument is needed.  Bytes past the pickled object's
    representation are ignored.

    Optional keyword arguments are *fix_imports*, *encoding* and *errors*,
    which are used to control compatibility support for pickle stream
    generated by Python 2.  If *fix_imports* is True, pickle will try to
    map the old Python 2 names to the new names used in Python 3.  The
    *encoding* and *errors* tell pickle how to decode 8-bit string
    instances pickled by Python 2; these default to 'ASCII' and 'strict',
    respectively.  The *encoding* can be 'bytes' to read these 8-bit
    string instances as bytes objects.

    *allow_pickle* must be true before any pickle opcodes are evaluated.
    It is false by default.
    """
    if type(allow_pickle) is not bool:
        raise TypeError("allow_pickle must be a bool")
    if not allow_pickle:
        raise PickleNotAllowedError(
            "automatic unpickling is disabled; reopen the file with "
            "allow_pickle=True only if the file is trusted"
        )

    kwargs = {
        "fix_imports": fix_imports,
        "encoding": encoding,
        "errors": errors,
    }
    # pandas.compat.pickle_compat.patch_pickle() temporarily replaces
    # pickle.loads with a compatibility loader that has no buffers argument.
    # Do not forward the unused default so trusted pandas reads keep working.
    if buffers is not None:
        kwargs["buffers"] = buffers
    return _pickle.loads(data, **kwargs)
