/* Generated by Pyrex 0.4.4 on Fri Oct  4 10:07:38 2002 */

#include "Python.h"
#include "stdlib.h"
#include "stdio.h"
#include "string.h"
#include "hdf5.h"
#include "H5LT.h"
#include "H5TB.h"
#include "calcoffset.h"
#include "getfieldfmt.h"
#include "utils.h"


static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, char *name); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static char *__pyx_srcfile = "src/hdf5Extension.pyx";
static int __pyx_lineno;
enum  {
  MAX_FIELDS = 255,
};
enum  {
  MAX_CHARS = 256,
};



staticforward PyTypeObject __pyx_type_File;

struct __pyx_obj_File {
  PyObject_HEAD
  int file_id;
  char (*name);
};

staticforward PyTypeObject __pyx_type_Group;

struct __pyx_obj_Group {
  PyObject_HEAD
  int group_id;
  char (*name);
};

staticforward PyTypeObject __pyx_type_Table;

struct __pyx_obj_Table {
  PyObject_HEAD
  int dst_size;
  int (field_offset[MAX_FIELDS]);
  int (field_sizes[MAX_FIELDS]);
  long long nfields;
  long long totalrecords;
  int group_id;
  int loc_id;
  char (*tablename);
  char (tabletitle[MAX_CHARS]);
  char (*fmt);
  char (*(*field_names));
  int compress;
};


static PyObject *__pyx_f_isHDF5(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_isHDF5(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char (*__pyx_v_filename);
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"filename",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "s", __pyx_argnames, &__pyx_v_filename)) return 0;

  /* "src/hdf5Extension.pyx":191 */
  __pyx_1 = PyInt_FromLong(H5Fis_hdf5(__pyx_v_filename)); if (!__pyx_1) {__pyx_lineno = 191; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("isHDF5");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static char (__pyx_k3[]) = "Problems getting the HDF5 library version.";
static char (__pyx_k4[]) = "%d.%d.%d";

static PyObject *__pyx_f_getHDF5Version(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_getHDF5Version[] = "Get the underlying HDF5 library version.";
static PyObject *__pyx_f_getHDF5Version(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  unsigned int __pyx_v_majnum;
  unsigned int __pyx_v_minnum;
  unsigned int __pyx_v_relnum;
  char (__pyx_v_buffer[MAX_CHARS]);
  int __pyx_v_ret;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;

  /* "src/hdf5Extension.pyx":195 */

  /* "src/hdf5Extension.pyx":196 */

  /* "src/hdf5Extension.pyx":197 */

  /* "src/hdf5Extension.pyx":199 */
  __pyx_v_ret = H5get_libversion((&__pyx_v_majnum),(&__pyx_v_minnum),(&__pyx_v_relnum));

  /* "src/hdf5Extension.pyx":200 */
  __pyx_1 = (__pyx_v_ret < 0);
  if (__pyx_1) {

    /* "src/hdf5Extension.pyx":201 */
    __pyx_2 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_2) {__pyx_lineno = 201; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(__pyx_k3); if (!__pyx_3) {__pyx_lineno = 201; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_lineno = 201; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_5 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_5) {__pyx_lineno = 201; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_lineno = 201; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "src/hdf5Extension.pyx":203 */
  snprintf(__pyx_v_buffer,MAX_CHARS,__pyx_k4,__pyx_v_majnum,__pyx_v_minnum,__pyx_v_relnum);

  /* "src/hdf5Extension.pyx":204 */
  __pyx_3 = PyString_FromString(__pyx_v_buffer); if (!__pyx_3) {__pyx_lineno = 204; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("getHDF5Version");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static char (__pyx_k5[]) = "$Id: hdf5Extension.c,v 1.2 2002/10/04 20:13:44 falted Exp $ ";

static PyObject *__pyx_f_getExtCVSVersion(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_getExtCVSVersion[] = " To guess this extension CVS version.";
static PyObject *__pyx_f_getExtCVSVersion(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;

  /* "src/hdf5Extension.pyx":215 */
  __pyx_1 = PyString_FromString(__pyx_k5); if (!__pyx_1) {__pyx_lineno = 215; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("getExtCVSVersion");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}


static PyObject *__pyx_f_getTablesVersion(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_getTablesVersion[] = "Returns this extension version.";
static PyObject *__pyx_f_getTablesVersion(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;

  /* "src/hdf5Extension.pyx":220 */
  __pyx_1 = _getTablesVersion(); if (!__pyx_1) {__pyx_lineno = 220; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("getTablesVersion");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static char (__pyx_k6[]) = "r";
static char (__pyx_k7[]) = "r+";
static char (__pyx_k8[]) = "r";
static char (__pyx_k9[]) = "r+";
static char (__pyx_k10[]) = "File %s doesn't exist or not a HDF5 file.";
static char (__pyx_k11[]) = "a";
static char (__pyx_k12[]) = "File %s exist but is not a HDF5 file.";
static char (__pyx_k13[]) = "w";
static char (__pyx_k14[]) = "Invalid mode %s for opening a file.";

static int __pyx_f_4File___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_4File___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char (*__pyx_v_name);
  char (*__pyx_v_mode);
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  PyObject *__pyx_8 = 0;
  int __pyx_9;
  static char *__pyx_argnames[] = {"name","mode",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "ss", __pyx_argnames, &__pyx_v_name, &__pyx_v_mode)) return -1;
  Py_INCREF(__pyx_v_self);

  /* "src/hdf5Extension.pyx":229 */
  ((struct __pyx_obj_File *)__pyx_v_self)->name = __pyx_v_name;

  /* "src/hdf5Extension.pyx":230 */
  __pyx_1 = PyString_FromString(__pyx_v_mode); if (!__pyx_1) {__pyx_lineno = 230; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_v_self, "mode", __pyx_1) < 0) {__pyx_lineno = 230; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "src/hdf5Extension.pyx":231 */
  if (!(__pyx_2 = (strcmp(__pyx_v_mode,__pyx_k6) == 0))) {
    __pyx_2 = (strcmp(__pyx_v_mode,__pyx_k7) == 0);
  }
  if (__pyx_2) {

    /* "src/hdf5Extension.pyx":232 */
    __pyx_1 = __Pyx_GetName(__pyx_m, "os"); if (!__pyx_1) {__pyx_lineno = 232; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttrString(__pyx_1, "path"); if (!__pyx_3) {__pyx_lineno = 232; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_4 = PyObject_GetAttrString(__pyx_3, "isfile"); if (!__pyx_4) {__pyx_lineno = 232; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_5 = PyString_FromString(__pyx_v_name); if (!__pyx_5) {__pyx_lineno = 232; goto __pyx_L1;}
    __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_lineno = 232; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_6, 0, __pyx_5);
    __pyx_5 = 0;
    __pyx_8 = PyObject_CallObject(__pyx_4, __pyx_6); if (!__pyx_8) {__pyx_lineno = 232; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_2 = PyObject_IsTrue(__pyx_8); if (__pyx_2 < 0) {__pyx_lineno = 232; goto __pyx_L1;}
    if (__pyx_2) {
      Py_DECREF(__pyx_8); __pyx_8 = 0;
      __pyx_8 = PyInt_FromLong((H5Fis_hdf5(__pyx_v_name) > 0)); if (!__pyx_8) {__pyx_lineno = 232; goto __pyx_L1;}
    }
    __pyx_9 = PyObject_IsTrue(__pyx_8); if (__pyx_9 < 0) {__pyx_lineno = 232; goto __pyx_L1;}
    Py_DECREF(__pyx_8); __pyx_8 = 0;
    if (__pyx_9) {

      /* "src/hdf5Extension.pyx":235 */
      __pyx_2 = (strcmp(__pyx_v_mode,__pyx_k8) == 0);
      if (__pyx_2) {

        /* "src/hdf5Extension.pyx":236 */
        ((struct __pyx_obj_File *)__pyx_v_self)->file_id = H5Fopen(__pyx_v_name,H5F_ACC_RDONLY,H5P_DEFAULT);
        goto __pyx_L4;
      }
      __pyx_9 = (strcmp(__pyx_v_mode,__pyx_k9) == 0);
      if (__pyx_9) {

        /* "src/hdf5Extension.pyx":238 */
        ((struct __pyx_obj_File *)__pyx_v_self)->file_id = H5Fopen(__pyx_v_name,H5F_ACC_RDWR,H5P_DEFAULT);
        goto __pyx_L4;
      }
      __pyx_L4:;
      goto __pyx_L3;
    }
    /*else*/ {

      /* "src/hdf5Extension.pyx":240 */
      __pyx_1 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_1) {__pyx_lineno = 240; goto __pyx_L1;}
      __pyx_3 = PyString_FromString(__pyx_k10); if (!__pyx_3) {__pyx_lineno = 240; goto __pyx_L1;}
      __pyx_5 = PyString_FromString(((struct __pyx_obj_File *)__pyx_v_self)->name); if (!__pyx_5) {__pyx_lineno = 240; goto __pyx_L1;}
      __pyx_6 = PyNumber_Remainder(__pyx_3, __pyx_5); if (!__pyx_6) {__pyx_lineno = 240; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_lineno = 240; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_4, 0, __pyx_6);
      __pyx_6 = 0;
      __pyx_7 = PyObject_CallObject(__pyx_1, __pyx_4); if (!__pyx_7) {__pyx_lineno = 240; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __Pyx_Raise(__pyx_7, 0, 0);
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      {__pyx_lineno = 240; goto __pyx_L1;}
    }
    __pyx_L3:;
    goto __pyx_L2;
  }
  __pyx_2 = (strcmp(__pyx_v_mode,__pyx_k11) == 0);
  if (__pyx_2) {

    /* "src/hdf5Extension.pyx":242 */
    __pyx_8 = __Pyx_GetName(__pyx_m, "os"); if (!__pyx_8) {__pyx_lineno = 242; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttrString(__pyx_8, "path"); if (!__pyx_3) {__pyx_lineno = 242; goto __pyx_L1;}
    Py_DECREF(__pyx_8); __pyx_8 = 0;
    __pyx_5 = PyObject_GetAttrString(__pyx_3, "isfile"); if (!__pyx_5) {__pyx_lineno = 242; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_6 = PyString_FromString(__pyx_v_name); if (!__pyx_6) {__pyx_lineno = 242; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_lineno = 242; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_6);
    __pyx_6 = 0;
    __pyx_1 = PyObject_CallObject(__pyx_5, __pyx_4); if (!__pyx_1) {__pyx_lineno = 242; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_9 = PyObject_IsTrue(__pyx_1); if (__pyx_9 < 0) {__pyx_lineno = 242; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    if (__pyx_9) {

      /* "src/hdf5Extension.pyx":243 */
      __pyx_2 = (H5Fis_hdf5(__pyx_v_name) > 0);
      if (__pyx_2) {

        /* "src/hdf5Extension.pyx":244 */
        ((struct __pyx_obj_File *)__pyx_v_self)->file_id = H5Fopen(__pyx_v_name,H5F_ACC_RDWR,H5P_DEFAULT);
        goto __pyx_L6;
      }
      /*else*/ {

        /* "src/hdf5Extension.pyx":246 */
        __pyx_7 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_7) {__pyx_lineno = 246; goto __pyx_L1;}
        __pyx_8 = PyString_FromString(__pyx_k12); if (!__pyx_8) {__pyx_lineno = 246; goto __pyx_L1;}
        __pyx_3 = PyString_FromString(((struct __pyx_obj_File *)__pyx_v_self)->name); if (!__pyx_3) {__pyx_lineno = 246; goto __pyx_L1;}
        __pyx_6 = PyNumber_Remainder(__pyx_8, __pyx_3); if (!__pyx_6) {__pyx_lineno = 246; goto __pyx_L1;}
        Py_DECREF(__pyx_8); __pyx_8 = 0;
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_lineno = 246; goto __pyx_L1;}
        PyTuple_SET_ITEM(__pyx_4, 0, __pyx_6);
        __pyx_6 = 0;
        __pyx_5 = PyObject_CallObject(__pyx_7, __pyx_4); if (!__pyx_5) {__pyx_lineno = 246; goto __pyx_L1;}
        Py_DECREF(__pyx_7); __pyx_7 = 0;
        Py_DECREF(__pyx_4); __pyx_4 = 0;
        __Pyx_Raise(__pyx_5, 0, 0);
        Py_DECREF(__pyx_5); __pyx_5 = 0;
        {__pyx_lineno = 246; goto __pyx_L1;}
      }
      __pyx_L6:;
      goto __pyx_L5;
    }
    /*else*/ {

      /* "src/hdf5Extension.pyx":248 */
      ((struct __pyx_obj_File *)__pyx_v_self)->file_id = H5Fcreate(__pyx_v_name,H5F_ACC_TRUNC,H5P_DEFAULT,H5P_DEFAULT);
    }
    __pyx_L5:;
    goto __pyx_L2;
  }
  __pyx_9 = (strcmp(__pyx_v_mode,__pyx_k13) == 0);
  if (__pyx_9) {

    /* "src/hdf5Extension.pyx":251 */
    ((struct __pyx_obj_File *)__pyx_v_self)->file_id = H5Fcreate(__pyx_v_name,H5F_ACC_TRUNC,H5P_DEFAULT,H5P_DEFAULT);
    goto __pyx_L2;
  }
  /*else*/ {

    /* "src/hdf5Extension.pyx":254 */
    __pyx_1 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_1) {__pyx_lineno = 254; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(__pyx_k14); if (!__pyx_3) {__pyx_lineno = 254; goto __pyx_L1;}
    __pyx_8 = PyObject_GetAttrString(__pyx_v_self, "mode"); if (!__pyx_8) {__pyx_lineno = 254; goto __pyx_L1;}
    __pyx_6 = PyNumber_Remainder(__pyx_3, __pyx_8); if (!__pyx_6) {__pyx_lineno = 254; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_8); __pyx_8 = 0;
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_lineno = 254; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_6);
    __pyx_6 = 0;
    __pyx_7 = PyObject_CallObject(__pyx_1, __pyx_4); if (!__pyx_7) {__pyx_lineno = 254; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_7, 0, 0);
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    {__pyx_lineno = 254; goto __pyx_L1;}
  }
  __pyx_L2:;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  Py_XDECREF(__pyx_8);
  __Pyx_AddTraceback("__new__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static PyObject *__pyx_f_4File_getFileId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4File_getFileId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "src/hdf5Extension.pyx":258 */
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_File *)__pyx_v_self)->file_id); if (!__pyx_1) {__pyx_lineno = 258; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("getFileId");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static PyObject *__pyx_f_4File_closeFile(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4File_closeFile(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "src/hdf5Extension.pyx":262 */
  H5Fclose(((struct __pyx_obj_File *)__pyx_v_self)->file_id);

  /* "src/hdf5Extension.pyx":263 */
  ((struct __pyx_obj_File *)__pyx_v_self)->file_id = 0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("closeFile");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static char (__pyx_k15[]) = "Closing the HDF5 file";
static char (__pyx_k16[]) = " because user didn't do that!.";
static char (__pyx_k17[]) = "Problems closing the file %s";

static void __pyx_f_4File___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_4File___dealloc__(PyObject *__pyx_v_self) {
  int __pyx_v_ret;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  Py_INCREF(__pyx_v_self);

  /* "src/hdf5Extension.pyx":266 */

  /* "src/hdf5Extension.pyx":268 */
  __pyx_1 = ((struct __pyx_obj_File *)__pyx_v_self)->file_id;
  if (__pyx_1) {

    /* "src/hdf5Extension.pyx":269 */
    __pyx_2 = PyString_FromString(__pyx_k15); if (!__pyx_2) {__pyx_lineno = 269; goto __pyx_L1;}
    if (__Pyx_PrintItem(__pyx_2) < 0) {__pyx_lineno = 269; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_2 = __Pyx_GetName(__pyx_b, "name"); if (!__pyx_2) {__pyx_lineno = 269; goto __pyx_L1;}
    if (__Pyx_PrintItem(__pyx_2) < 0) {__pyx_lineno = 269; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_2 = PyString_FromString(__pyx_k16); if (!__pyx_2) {__pyx_lineno = 269; goto __pyx_L1;}
    if (__Pyx_PrintItem(__pyx_2) < 0) {__pyx_lineno = 269; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (__Pyx_PrintNewline() < 0) {__pyx_lineno = 269; goto __pyx_L1;}

    /* "src/hdf5Extension.pyx":270 */
    __pyx_v_ret = H5Fclose(((struct __pyx_obj_File *)__pyx_v_self)->file_id);

    /* "src/hdf5Extension.pyx":271 */
    __pyx_1 = (__pyx_v_ret < 0);
    if (__pyx_1) {

      /* "src/hdf5Extension.pyx":272 */
      __pyx_2 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_2) {__pyx_lineno = 272; goto __pyx_L1;}
      __pyx_3 = PyString_FromString(__pyx_k17); if (!__pyx_3) {__pyx_lineno = 272; goto __pyx_L1;}
      __pyx_4 = PyString_FromString(((struct __pyx_obj_File *)__pyx_v_self)->name); if (!__pyx_4) {__pyx_lineno = 272; goto __pyx_L1;}
      __pyx_5 = PyNumber_Remainder(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_lineno = 272; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_lineno = 272; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_6, 0, __pyx_5);
      __pyx_5 = 0;
      __pyx_7 = PyObject_CallObject(__pyx_2, __pyx_6); if (!__pyx_7) {__pyx_lineno = 272; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      __Pyx_Raise(__pyx_7, 0, 0);
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      {__pyx_lineno = 272; goto __pyx_L1;}
      goto __pyx_L3;
    }
    __pyx_L3:;
    goto __pyx_L2;
  }
  __pyx_L2:;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_WriteUnraisable("hdf5Extension.__dealloc__");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
}

static char (__pyx_k18[]) = "";

static int __pyx_f_5Group___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_5Group___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return -1;
  Py_INCREF(__pyx_v_self);

  /* "src/hdf5Extension.pyx":281 */
  ((struct __pyx_obj_Group *)__pyx_v_self)->name = strdup(__pyx_k18);

  /* "src/hdf5Extension.pyx":282 */
  ((struct __pyx_obj_Group *)__pyx_v_self)->group_id = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("__new__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static char (__pyx_k19[]) = "Can't create the group %s.";

static PyObject *__pyx_f_5Group__f_createGroup(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5Group__f_createGroup(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_loc_id;
  char (*__pyx_v_name);
  int __pyx_v_ret;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  static char *__pyx_argnames[] = {"loc_id","name",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "is", __pyx_argnames, &__pyx_v_loc_id, &__pyx_v_name)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "src/hdf5Extension.pyx":285 */

  /* "src/hdf5Extension.pyx":288 */
  ((struct __pyx_obj_Group *)__pyx_v_self)->name = strdup(__pyx_v_name);

  /* "src/hdf5Extension.pyx":289 */
  __pyx_v_ret = H5Gcreate(__pyx_v_loc_id,__pyx_v_name,0);

  /* "src/hdf5Extension.pyx":290 */
  __pyx_1 = (__pyx_v_ret < 0);
  if (__pyx_1) {

    /* "src/hdf5Extension.pyx":291 */
    __pyx_2 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_2) {__pyx_lineno = 291; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(__pyx_k19); if (!__pyx_3) {__pyx_lineno = 291; goto __pyx_L1;}
    __pyx_4 = PyString_FromString(((struct __pyx_obj_Group *)__pyx_v_self)->name); if (!__pyx_4) {__pyx_lineno = 291; goto __pyx_L1;}
    __pyx_5 = PyNumber_Remainder(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_lineno = 291; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_lineno = 291; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_6, 0, __pyx_5);
    __pyx_5 = 0;
    __pyx_7 = PyObject_CallObject(__pyx_2, __pyx_6); if (!__pyx_7) {__pyx_lineno = 291; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __Pyx_Raise(__pyx_7, 0, 0);
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    {__pyx_lineno = 291; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "src/hdf5Extension.pyx":292 */
  ((struct __pyx_obj_Group *)__pyx_v_self)->group_id = __pyx_v_ret;

  /* "src/hdf5Extension.pyx":293 */
  __pyx_3 = PyInt_FromLong(((struct __pyx_obj_Group *)__pyx_v_self)->group_id); if (!__pyx_3) {__pyx_lineno = 293; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("_f_createGroup");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static char (__pyx_k20[]) = "Can't open the group %s.";

static PyObject *__pyx_f_5Group__f_openGroup(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5Group__f_openGroup(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_loc_id;
  char (*__pyx_v_name);
  int __pyx_v_ret;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  static char *__pyx_argnames[] = {"loc_id","name",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "is", __pyx_argnames, &__pyx_v_loc_id, &__pyx_v_name)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "src/hdf5Extension.pyx":296 */

  /* "src/hdf5Extension.pyx":299 */
  ((struct __pyx_obj_Group *)__pyx_v_self)->name = strdup(__pyx_v_name);

  /* "src/hdf5Extension.pyx":300 */
  __pyx_v_ret = H5Gopen(__pyx_v_loc_id,__pyx_v_name);

  /* "src/hdf5Extension.pyx":301 */
  __pyx_1 = (__pyx_v_ret < 0);
  if (__pyx_1) {

    /* "src/hdf5Extension.pyx":302 */
    __pyx_2 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_2) {__pyx_lineno = 302; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(__pyx_k20); if (!__pyx_3) {__pyx_lineno = 302; goto __pyx_L1;}
    __pyx_4 = PyString_FromString(((struct __pyx_obj_Group *)__pyx_v_self)->name); if (!__pyx_4) {__pyx_lineno = 302; goto __pyx_L1;}
    __pyx_5 = PyNumber_Remainder(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_lineno = 302; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_lineno = 302; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_6, 0, __pyx_5);
    __pyx_5 = 0;
    __pyx_7 = PyObject_CallObject(__pyx_2, __pyx_6); if (!__pyx_7) {__pyx_lineno = 302; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __Pyx_Raise(__pyx_7, 0, 0);
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    {__pyx_lineno = 302; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "src/hdf5Extension.pyx":303 */
  ((struct __pyx_obj_Group *)__pyx_v_self)->group_id = __pyx_v_ret;

  /* "src/hdf5Extension.pyx":304 */
  __pyx_3 = PyInt_FromLong(((struct __pyx_obj_Group *)__pyx_v_self)->group_id); if (!__pyx_3) {__pyx_lineno = 304; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("_f_openGroup");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static PyObject *__pyx_f_5Group__f_listGroup(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5Group__f_listGroup(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_loc_id;
  char (*__pyx_v_name);
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"loc_id","name",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "is", __pyx_argnames, &__pyx_v_loc_id, &__pyx_v_name)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "src/hdf5Extension.pyx":308 */
  __pyx_1 = Giterate(__pyx_v_loc_id,__pyx_v_name); if (!__pyx_1) {__pyx_lineno = 308; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("_f_listGroup");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static PyObject *__pyx_f_5Group__f_getGroupId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5Group__f_getGroupId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "src/hdf5Extension.pyx":311 */
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_Group *)__pyx_v_self)->group_id); if (!__pyx_1) {__pyx_lineno = 311; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("_f_getGroupId");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static PyObject *__pyx_f_5Group__f_getGroupName(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5Group__f_getGroupName(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "src/hdf5Extension.pyx":314 */
  __pyx_1 = PyString_FromString(((struct __pyx_obj_Group *)__pyx_v_self)->name); if (!__pyx_1) {__pyx_lineno = 314; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("_f_getGroupName");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static char (__pyx_k21[]) = "";
static char (__pyx_k22[]) = "Problems closing the group %s";

static void __pyx_f_5Group___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_5Group___dealloc__(PyObject *__pyx_v_self) {
  int __pyx_v_ret;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  Py_INCREF(__pyx_v_self);

  /* "src/hdf5Extension.pyx":317 */

  /* "src/hdf5Extension.pyx":319 */
  __pyx_1 = (strcmp(((struct __pyx_obj_Group *)__pyx_v_self)->name,__pyx_k21) != 0);
  if (__pyx_1) {

    /* "src/hdf5Extension.pyx":321 */
    __pyx_1 = ((struct __pyx_obj_Group *)__pyx_v_self)->group_id;
    if (__pyx_1) {

      /* "src/hdf5Extension.pyx":322 */
      __pyx_v_ret = H5Gclose(((struct __pyx_obj_Group *)__pyx_v_self)->group_id);

      /* "src/hdf5Extension.pyx":323 */
      __pyx_1 = (__pyx_v_ret < 0);
      if (__pyx_1) {

        /* "src/hdf5Extension.pyx":324 */
        __pyx_2 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_2) {__pyx_lineno = 324; goto __pyx_L1;}
        __pyx_3 = PyString_FromString(__pyx_k22); if (!__pyx_3) {__pyx_lineno = 324; goto __pyx_L1;}
        __pyx_4 = PyString_FromString(((struct __pyx_obj_Group *)__pyx_v_self)->name); if (!__pyx_4) {__pyx_lineno = 324; goto __pyx_L1;}
        __pyx_5 = PyNumber_Remainder(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_lineno = 324; goto __pyx_L1;}
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        Py_DECREF(__pyx_4); __pyx_4 = 0;
        __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_lineno = 324; goto __pyx_L1;}
        PyTuple_SET_ITEM(__pyx_6, 0, __pyx_5);
        __pyx_5 = 0;
        __pyx_7 = PyObject_CallObject(__pyx_2, __pyx_6); if (!__pyx_7) {__pyx_lineno = 324; goto __pyx_L1;}
        Py_DECREF(__pyx_2); __pyx_2 = 0;
        Py_DECREF(__pyx_6); __pyx_6 = 0;
        __Pyx_Raise(__pyx_7, 0, 0);
        Py_DECREF(__pyx_7); __pyx_7 = 0;
        {__pyx_lineno = 324; goto __pyx_L1;}
        goto __pyx_L4;
      }
      __pyx_L4:;
      goto __pyx_L3;
    }
    __pyx_L3:;
    goto __pyx_L2;
  }
  /*else*/ {
  }
  __pyx_L2:;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_WriteUnraisable("hdf5Extension.__dealloc__");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
}

static char (__pyx_k23[]) = "";

static int __pyx_f_5Table___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_5Table___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_where = 0;
  PyObject *__pyx_v_name = 0;
  PyObject *__pyx_v_rootgroup = 0;
  PyObject *__pyx_v_group;
  int __pyx_r;
  char (*__pyx_1);
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  PyObject *__pyx_8 = 0;
  int __pyx_9;
  static char *__pyx_argnames[] = {"where","name","rootgroup",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_where, &__pyx_v_name, &__pyx_v_rootgroup)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_where);
  Py_INCREF(__pyx_v_name);
  Py_INCREF(__pyx_v_rootgroup);
  __pyx_v_group = Py_None; Py_INCREF(__pyx_v_group);

  /* "src/hdf5Extension.pyx":347 */
  __pyx_1 = PyString_AsString(__pyx_v_name); if (PyErr_Occurred()) {__pyx_lineno = 347; goto __pyx_L1;}
  ((struct __pyx_obj_Table *)__pyx_v_self)->tablename = strdup(__pyx_1);

  /* "src/hdf5Extension.pyx":351 */
  __pyx_2 = __Pyx_GetName(__pyx_b, "type"); if (!__pyx_2) {__pyx_lineno = 351; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_lineno = 351; goto __pyx_L1;}
  Py_INCREF(__pyx_v_where);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_where);
  __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_lineno = 351; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_5 = __Pyx_GetName(__pyx_b, "type"); if (!__pyx_5) {__pyx_lineno = 351; goto __pyx_L1;}
  __pyx_6 = PyString_FromString(__pyx_k23); if (!__pyx_6) {__pyx_lineno = 351; goto __pyx_L1;}
  __pyx_7 = PyTuple_New(1); if (!__pyx_7) {__pyx_lineno = 351; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_7, 0, __pyx_6);
  __pyx_6 = 0;
  __pyx_8 = PyObject_CallObject(__pyx_5, __pyx_7); if (!__pyx_8) {__pyx_lineno = 351; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  if (PyObject_Cmp(__pyx_4, __pyx_8, &__pyx_9) < 0) {__pyx_lineno = 351; goto __pyx_L1;}
  __pyx_9 = __pyx_9 == 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_8); __pyx_8 = 0;
  if (__pyx_9) {

    /* "src/hdf5Extension.pyx":352 */
    __pyx_3 = PyObject_GetAttrString(__pyx_v_rootgroup, "_f_getObjectFromPath"); if (!__pyx_3) {__pyx_lineno = 352; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_lineno = 352; goto __pyx_L1;}
    Py_INCREF(__pyx_v_where);
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_where);
    __pyx_6 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_6) {__pyx_lineno = 352; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_v_group);
    __pyx_v_group = __pyx_6;
    __pyx_6 = 0;

    /* "src/hdf5Extension.pyx":353 */
    __pyx_7 = PyObject_GetAttrString(__pyx_v_group, "_v_groupId"); if (!__pyx_7) {__pyx_lineno = 353; goto __pyx_L1;}
    __pyx_9 = PyInt_AsLong(__pyx_7); if (PyErr_Occurred()) {__pyx_lineno = 353; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    ((struct __pyx_obj_Table *)__pyx_v_self)->group_id = __pyx_9;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "src/hdf5Extension.pyx":355 */
    __pyx_5 = PyObject_GetAttrString(__pyx_v_where, "_v_groupId"); if (!__pyx_5) {__pyx_lineno = 355; goto __pyx_L1;}
    __pyx_9 = PyInt_AsLong(__pyx_5); if (PyErr_Occurred()) {__pyx_lineno = 355; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    ((struct __pyx_obj_Table *)__pyx_v_self)->group_id = __pyx_9;
  }
  __pyx_L2:;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  Py_XDECREF(__pyx_8);
  __Pyx_AddTraceback("__new__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_group);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_where);
  Py_DECREF(__pyx_v_name);
  Py_DECREF(__pyx_v_rootgroup);
  return __pyx_r;
}

static char (__pyx_k24[]) = "Problems opening the table";
static char (__pyx_k25[]) = "TITLE";
static char (__pyx_k26[]) = "Problems getting table TITLE attribute";

static PyObject *__pyx_f_5Table_openTable(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5Table_openTable[] = " Open the table, and read the table TITLE attribute.";
static PyObject *__pyx_f_5Table_openTable(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_ret;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "src/hdf5Extension.pyx":359 */

  /* "src/hdf5Extension.pyx":363 */
  ((struct __pyx_obj_Table *)__pyx_v_self)->loc_id = H5Dopen(((struct __pyx_obj_Table *)__pyx_v_self)->group_id,((struct __pyx_obj_Table *)__pyx_v_self)->tablename);

  /* "src/hdf5Extension.pyx":364 */
  __pyx_1 = (((struct __pyx_obj_Table *)__pyx_v_self)->loc_id < 0);
  if (__pyx_1) {

    /* "src/hdf5Extension.pyx":365 */
    __pyx_2 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_2) {__pyx_lineno = 365; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(__pyx_k24); if (!__pyx_3) {__pyx_lineno = 365; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_lineno = 365; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_5 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_5) {__pyx_lineno = 365; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_lineno = 365; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "src/hdf5Extension.pyx":367 */
  __pyx_v_ret = H5LTget_attribute(((struct __pyx_obj_Table *)__pyx_v_self)->loc_id,__pyx_k25,((struct __pyx_obj_Table *)__pyx_v_self)->tabletitle);

  /* "src/hdf5Extension.pyx":368 */
  __pyx_1 = (__pyx_v_ret < 0);
  if (__pyx_1) {

    /* "src/hdf5Extension.pyx":369 */
    __pyx_3 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_3) {__pyx_lineno = 369; goto __pyx_L1;}
    __pyx_4 = PyString_FromString(__pyx_k26); if (!__pyx_4) {__pyx_lineno = 369; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_lineno = 369; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
    __pyx_4 = 0;
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_5) {__pyx_lineno = 369; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_lineno = 369; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("openTable");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static char (__pyx_k27[]) = "Problems closing the table";

static PyObject *__pyx_f_5Table_closeTable(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5Table_closeTable(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_ret;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "src/hdf5Extension.pyx":372 */

  /* "src/hdf5Extension.pyx":374 */
  __pyx_v_ret = H5Dclose(((struct __pyx_obj_Table *)__pyx_v_self)->loc_id);

  /* "src/hdf5Extension.pyx":375 */
  __pyx_1 = (__pyx_v_ret < 0);
  if (__pyx_1) {

    /* "src/hdf5Extension.pyx":376 */
    __pyx_2 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_2) {__pyx_lineno = 376; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(__pyx_k27); if (!__pyx_3) {__pyx_lineno = 376; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_lineno = 376; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_5 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_5) {__pyx_lineno = 376; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_lineno = 376; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("closeTable");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static char (__pyx_k28[]) = "Maximum of %d fields on struct allowed";
static char (__pyx_k29[]) = "nvar: ";
static char (__pyx_k30[]) = "nfields: ";
static char (__pyx_k31[]) = "Format and varnames differ in variable number";
static char (__pyx_k32[]) = "Problems creating the table";

static PyObject *__pyx_f_5Table_createTable(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5Table_createTable(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyTupleObject *__pyx_v_varnames = 0;
  char (*__pyx_v_fmt);
  char (*__pyx_v_tableTitle);
  int __pyx_v_compress;
  int __pyx_v_rowsize;
  long long __pyx_v_chunksize;
  int __pyx_v_nvar;
  int __pyx_v_i;
  int __pyx_v_nrecords;
  int __pyx_v_ret;
  int (__pyx_v_fieldtypes[MAX_FIELDS]);
  char (*__pyx_v_fill_data);
  char (*__pyx_v_data);
  PyObject *__pyx_v_name;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  PyObject *__pyx_8 = 0;
  char (*__pyx_9);
  static char *__pyx_argnames[] = {"varnames","fmt","tableTitle","compress","rowsize","chunksize",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OssiiL", __pyx_argnames, &__pyx_v_varnames, &__pyx_v_fmt, &__pyx_v_tableTitle, &__pyx_v_compress, &__pyx_v_rowsize, &__pyx_v_chunksize)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_varnames);
  __pyx_v_name = Py_None; Py_INCREF(__pyx_v_name);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_varnames), &PyTuple_Type, "varnames")) {__pyx_lineno = 379; goto __pyx_L1;}

  /* "src/hdf5Extension.pyx":382 */

  /* "src/hdf5Extension.pyx":383 */

  /* "src/hdf5Extension.pyx":384 */

  /* "src/hdf5Extension.pyx":385 */

  /* "src/hdf5Extension.pyx":388 */
  ((struct __pyx_obj_Table *)__pyx_v_self)->fmt = __pyx_v_fmt;

  /* "src/hdf5Extension.pyx":389 */
  ((struct __pyx_obj_Table *)__pyx_v_self)->compress = __pyx_v_compress;

  /* "src/hdf5Extension.pyx":391 */
  strncpy(((struct __pyx_obj_Table *)__pyx_v_self)->tabletitle,__pyx_v_tableTitle,MAX_CHARS);

  /* "src/hdf5Extension.pyx":394 */
  ((struct __pyx_obj_Table *)__pyx_v_self)->nfields = ((PyTupleObject *)((PyObject *)__pyx_v_varnames))->ob_size;

  /* "src/hdf5Extension.pyx":398 */
  ((struct __pyx_obj_Table *)__pyx_v_self)->field_names = ((char (*(*)))malloc((((struct __pyx_obj_Table *)__pyx_v_self)->nfields * (sizeof(char (*))))));

  /* "src/hdf5Extension.pyx":400 */
  __pyx_v_i = 0;

  /* "src/hdf5Extension.pyx":401 */
  __pyx_1 = PyObject_GetIter(((PyObject *)__pyx_v_varnames)); if (!__pyx_1) {__pyx_lineno = 401; goto __pyx_L1;}
  for (;;) {
    __pyx_L2:;
    __pyx_2 = PyIter_Next(__pyx_1);
    if (!__pyx_2) {
      if (PyErr_Occurred()) {__pyx_lineno = 401; goto __pyx_L1;}
      break;
    }
    Py_DECREF(__pyx_v_name);
    __pyx_v_name = __pyx_2;
    __pyx_2 = 0;

    /* "src/hdf5Extension.pyx":403 */
    __pyx_3 = (__pyx_v_i > MAX_FIELDS);
    if (__pyx_3) {

      /* "src/hdf5Extension.pyx":404 */
      __pyx_2 = __Pyx_GetName(__pyx_b, "IndexError"); if (!__pyx_2) {__pyx_lineno = 404; goto __pyx_L1;}
      __pyx_4 = PyString_FromString(__pyx_k28); if (!__pyx_4) {__pyx_lineno = 404; goto __pyx_L1;}
      __pyx_5 = PyInt_FromLong(MAX_FIELDS); if (!__pyx_5) {__pyx_lineno = 404; goto __pyx_L1;}
      __pyx_6 = PyNumber_Remainder(__pyx_4, __pyx_5); if (!__pyx_6) {__pyx_lineno = 404; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_7 = PyTuple_New(1); if (!__pyx_7) {__pyx_lineno = 404; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_7, 0, __pyx_6);
      __pyx_6 = 0;
      __pyx_8 = PyObject_CallObject(__pyx_2, __pyx_7); if (!__pyx_8) {__pyx_lineno = 404; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      __Pyx_Raise(__pyx_8, 0, 0);
      Py_DECREF(__pyx_8); __pyx_8 = 0;
      {__pyx_lineno = 404; goto __pyx_L1;}
      goto __pyx_L4;
    }
    __pyx_L4:;

    /* "src/hdf5Extension.pyx":405 */
    __pyx_9 = PyString_AsString(__pyx_v_name); if (PyErr_Occurred()) {__pyx_lineno = 405; goto __pyx_L1;}
    (((struct __pyx_obj_Table *)__pyx_v_self)->field_names[__pyx_v_i]) = __pyx_9;

    /* "src/hdf5Extension.pyx":406 */
    __pyx_v_i = (__pyx_v_i + 1);
  }
  __pyx_L3:;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "src/hdf5Extension.pyx":411 */
  __pyx_v_nvar = calcoffset(((struct __pyx_obj_Table *)__pyx_v_self)->fmt,((struct __pyx_obj_Table *)__pyx_v_self)->field_offset);

  /* "src/hdf5Extension.pyx":414 */
  __pyx_v_rowsize = calctypes(((struct __pyx_obj_Table *)__pyx_v_self)->fmt,__pyx_v_fieldtypes,((struct __pyx_obj_Table *)__pyx_v_self)->field_sizes);

  /* "src/hdf5Extension.pyx":415 */
  ((struct __pyx_obj_Table *)__pyx_v_self)->dst_size = __pyx_v_rowsize;

  /* "src/hdf5Extension.pyx":417 */
  __pyx_3 = (__pyx_v_nvar != ((struct __pyx_obj_Table *)__pyx_v_self)->nfields);
  if (__pyx_3) {

    /* "src/hdf5Extension.pyx":418 */
    __pyx_4 = PyString_FromString(__pyx_k29); if (!__pyx_4) {__pyx_lineno = 418; goto __pyx_L1;}
    if (__Pyx_PrintItem(__pyx_4) < 0) {__pyx_lineno = 418; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_5 = PyInt_FromLong(__pyx_v_nvar); if (!__pyx_5) {__pyx_lineno = 418; goto __pyx_L1;}
    if (__Pyx_PrintItem(__pyx_5) < 0) {__pyx_lineno = 418; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_6 = PyString_FromString(__pyx_k30); if (!__pyx_6) {__pyx_lineno = 418; goto __pyx_L1;}
    if (__Pyx_PrintItem(__pyx_6) < 0) {__pyx_lineno = 418; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_7 = PyInt_FromLong(((struct __pyx_obj_Table *)__pyx_v_self)->nfields); if (!__pyx_7) {__pyx_lineno = 418; goto __pyx_L1;}
    if (__Pyx_PrintItem(__pyx_7) < 0) {__pyx_lineno = 418; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    if (__Pyx_PrintNewline() < 0) {__pyx_lineno = 418; goto __pyx_L1;}

    /* "src/hdf5Extension.pyx":419 */
    __pyx_2 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_2) {__pyx_lineno = 419; goto __pyx_L1;}
    __pyx_8 = PyString_FromString(__pyx_k31); if (!__pyx_8) {__pyx_lineno = 419; goto __pyx_L1;}
    __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_lineno = 419; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_8);
    __pyx_8 = 0;
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_4) {__pyx_lineno = 419; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __Pyx_Raise(__pyx_4, 0, 0);
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_lineno = 419; goto __pyx_L1;}
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "src/hdf5Extension.pyx":427 */
  __pyx_v_nrecords = 0;

  /* "src/hdf5Extension.pyx":428 */
  __pyx_v_fill_data = 0;

  /* "src/hdf5Extension.pyx":429 */
  __pyx_v_data = 0;

  /* "src/hdf5Extension.pyx":430 */
  __pyx_v_ret = H5TBmake_table(((struct __pyx_obj_Table *)__pyx_v_self)->tabletitle,((struct __pyx_obj_Table *)__pyx_v_self)->group_id,((struct __pyx_obj_Table *)__pyx_v_self)->tablename,__pyx_v_nvar,__pyx_v_nrecords,__pyx_v_rowsize,((char (*(*)))((struct __pyx_obj_Table *)__pyx_v_self)->field_names),((struct __pyx_obj_Table *)__pyx_v_self)->field_offset,__pyx_v_fieldtypes,__pyx_v_chunksize,__pyx_v_fill_data,((struct __pyx_obj_Table *)__pyx_v_self)->compress,__pyx_v_data);

  /* "src/hdf5Extension.pyx":434 */
  __pyx_3 = (__pyx_v_ret < 0);
  if (__pyx_3) {

    /* "src/hdf5Extension.pyx":435 */
    __pyx_5 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_5) {__pyx_lineno = 435; goto __pyx_L1;}
    __pyx_6 = PyString_FromString(__pyx_k32); if (!__pyx_6) {__pyx_lineno = 435; goto __pyx_L1;}
    __pyx_7 = PyTuple_New(1); if (!__pyx_7) {__pyx_lineno = 435; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_7, 0, __pyx_6);
    __pyx_6 = 0;
    __pyx_8 = PyObject_CallObject(__pyx_5, __pyx_7); if (!__pyx_8) {__pyx_lineno = 435; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __Pyx_Raise(__pyx_8, 0, 0);
    Py_DECREF(__pyx_8); __pyx_8 = 0;
    {__pyx_lineno = 435; goto __pyx_L1;}
    goto __pyx_L6;
  }
  __pyx_L6:;

  /* "src/hdf5Extension.pyx":437 */
  ((struct __pyx_obj_Table *)__pyx_v_self)->totalrecords = 0;

  /* "src/hdf5Extension.pyx":439 */
  __pyx_1 = PyObject_GetAttrString(__pyx_v_self, "openTable"); if (!__pyx_1) {__pyx_lineno = 439; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_lineno = 439; goto __pyx_L1;}
  __pyx_4 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_4) {__pyx_lineno = 439; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  Py_XDECREF(__pyx_8);
  __Pyx_AddTraceback("createTable");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_name);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_varnames);
  return __pyx_r;
}

static char (__pyx_k33[]) = "Problems appending the record";

static PyObject *__pyx_f_5Table_append_record(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5Table_append_record(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyStringObject *__pyx_v_record = 0;
  int __pyx_v_ret;
  int __pyx_v_len;
  char (*__pyx_v_str);
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"record",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_record)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_record);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_record), &PyString_Type, "record")) {__pyx_lineno = 441; goto __pyx_L1;}

  /* "src/hdf5Extension.pyx":442 */

  /* "src/hdf5Extension.pyx":443 */

  /* "src/hdf5Extension.pyx":445 */
  __pyx_v_str = ((PyStringObject *)((PyObject *)__pyx_v_record))->ob_sval;

  /* "src/hdf5Extension.pyx":446 */
  __pyx_v_len = ((PyStringObject *)((PyObject *)__pyx_v_record))->ob_size;

  /* "src/hdf5Extension.pyx":448 */
  __pyx_v_ret = H5TBappend_records(((struct __pyx_obj_Table *)__pyx_v_self)->group_id,((struct __pyx_obj_Table *)__pyx_v_self)->tablename,1,((struct __pyx_obj_Table *)__pyx_v_self)->dst_size,((struct __pyx_obj_Table *)__pyx_v_self)->field_offset,((void (*))__pyx_v_str));

  /* "src/hdf5Extension.pyx":450 */
  __pyx_1 = (__pyx_v_ret < 0);
  if (__pyx_1) {

    /* "src/hdf5Extension.pyx":451 */
    __pyx_2 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_2) {__pyx_lineno = 451; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(__pyx_k33); if (!__pyx_3) {__pyx_lineno = 451; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_lineno = 451; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_5 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_5) {__pyx_lineno = 451; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_lineno = 451; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "src/hdf5Extension.pyx":452 */
  ((struct __pyx_obj_Table *)__pyx_v_self)->totalrecords = (((struct __pyx_obj_Table *)__pyx_v_self)->totalrecords + 1);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("append_record");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_record);
  return __pyx_r;
}

static char (__pyx_k34[]) = "Problems appending the records";

static PyObject *__pyx_f_5Table_append_records(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5Table_append_records(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyStringObject *__pyx_v_records = 0;
  int __pyx_v_nrecords;
  int __pyx_v_ret;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"records","nrecords",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "Oi", __pyx_argnames, &__pyx_v_records, &__pyx_v_nrecords)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_records);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_records), &PyString_Type, "records")) {__pyx_lineno = 454; goto __pyx_L1;}

  /* "src/hdf5Extension.pyx":455 */

  /* "src/hdf5Extension.pyx":459 */
  __pyx_v_ret = H5TBappend_records(((struct __pyx_obj_Table *)__pyx_v_self)->group_id,((struct __pyx_obj_Table *)__pyx_v_self)->tablename,__pyx_v_nrecords,((struct __pyx_obj_Table *)__pyx_v_self)->dst_size,((struct __pyx_obj_Table *)__pyx_v_self)->field_offset,((void (*))((PyStringObject *)((PyObject *)__pyx_v_records))->ob_sval));

  /* "src/hdf5Extension.pyx":461 */
  __pyx_1 = (__pyx_v_ret < 0);
  if (__pyx_1) {

    /* "src/hdf5Extension.pyx":462 */
    __pyx_2 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_2) {__pyx_lineno = 462; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(__pyx_k34); if (!__pyx_3) {__pyx_lineno = 462; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_lineno = 462; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_5 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_5) {__pyx_lineno = 462; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_lineno = 462; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "src/hdf5Extension.pyx":464 */
  ((struct __pyx_obj_Table *)__pyx_v_self)->totalrecords = (((struct __pyx_obj_Table *)__pyx_v_self)->totalrecords + __pyx_v_nrecords);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("append_records");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_records);
  return __pyx_r;
}


static PyObject *__pyx_f_5Table_getTableTitle(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5Table_getTableTitle[] = "Get the attribute TITLE from table. The maximum TITLE size is MAX_CHARS.";
static PyObject *__pyx_f_5Table_getTableTitle(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "src/hdf5Extension.pyx":468 */
  __pyx_1 = PyString_FromString(((struct __pyx_obj_Table *)__pyx_v_self)->tabletitle); if (!__pyx_1) {__pyx_lineno = 468; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("getTableTitle");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static char (__pyx_k35[]) = "Problems getting table dataset info";
static char (__pyx_k36[]) = "Problems getting table info";
static char (__pyx_k37[]) = "Problems getting field info";
static char (__pyx_k38[]) = "Problems getting field format";

static PyObject *__pyx_f_5Table_getTableInfo(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5Table_getTableInfo[] = "Get info from a table on disk. This method is standalone.";
static PyObject *__pyx_f_5Table_getTableInfo(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_i;
  int __pyx_v_ret;
  long long __pyx_v_nrecords;
  long long __pyx_v_nfields;
  long long (__pyx_v_dims[1]);
  enum H5T_class_t __pyx_v_class_id;
  PyObject *__pyx_v_read_buffer;
  PyObject *__pyx_v_names_tuple;
  int __pyx_v_rowsize;
  int (__pyx_v_field_offsets[MAX_FIELDS]);
  int (__pyx_v_fieldtypes[MAX_FIELDS]);
  int (__pyx_v_field_sizes[MAX_FIELDS]);
  char (*(*__pyx_v_field_names));
  char (__pyx_v_fmt[255]);
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_read_buffer = Py_None; Py_INCREF(__pyx_v_read_buffer);
  __pyx_v_names_tuple = Py_None; Py_INCREF(__pyx_v_names_tuple);

  /* "src/hdf5Extension.pyx":472 */

  /* "src/hdf5Extension.pyx":473 */

  /* "src/hdf5Extension.pyx":474 */

  /* "src/hdf5Extension.pyx":475 */

  /* "src/hdf5Extension.pyx":476 */

  /* "src/hdf5Extension.pyx":477 */

  /* "src/hdf5Extension.pyx":478 */

  /* "src/hdf5Extension.pyx":479 */

  /* "src/hdf5Extension.pyx":480 */

  /* "src/hdf5Extension.pyx":481 */

  /* "src/hdf5Extension.pyx":482 */

  /* "src/hdf5Extension.pyx":485 */
  __pyx_v_ret = H5LTget_dataset_info(((struct __pyx_obj_Table *)__pyx_v_self)->group_id,((struct __pyx_obj_Table *)__pyx_v_self)->tablename,__pyx_v_dims,(&__pyx_v_class_id),(&__pyx_v_rowsize));

  /* "src/hdf5Extension.pyx":487 */
  __pyx_1 = (__pyx_v_ret < 0);
  if (__pyx_1) {

    /* "src/hdf5Extension.pyx":488 */
    __pyx_2 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_2) {__pyx_lineno = 488; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(__pyx_k35); if (!__pyx_3) {__pyx_lineno = 488; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_lineno = 488; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_5 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_5) {__pyx_lineno = 488; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_lineno = 488; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "src/hdf5Extension.pyx":489 */
  ((struct __pyx_obj_Table *)__pyx_v_self)->dst_size = __pyx_v_rowsize;

  /* "src/hdf5Extension.pyx":495 */
  __pyx_v_ret = H5TBget_table_info(((struct __pyx_obj_Table *)__pyx_v_self)->group_id,((struct __pyx_obj_Table *)__pyx_v_self)->tablename,(&__pyx_v_nfields),(&__pyx_v_nrecords));

  /* "src/hdf5Extension.pyx":497 */
  __pyx_1 = (__pyx_v_ret < 0);
  if (__pyx_1) {

    /* "src/hdf5Extension.pyx":498 */
    __pyx_3 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_3) {__pyx_lineno = 498; goto __pyx_L1;}
    __pyx_4 = PyString_FromString(__pyx_k36); if (!__pyx_4) {__pyx_lineno = 498; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_lineno = 498; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
    __pyx_4 = 0;
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_5) {__pyx_lineno = 498; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_lineno = 498; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "src/hdf5Extension.pyx":499 */
  ((struct __pyx_obj_Table *)__pyx_v_self)->nfields = __pyx_v_nfields;

  /* "src/hdf5Extension.pyx":500 */
  ((struct __pyx_obj_Table *)__pyx_v_self)->totalrecords = __pyx_v_nrecords;

  /* "src/hdf5Extension.pyx":506 */
  __pyx_v_field_names = ((char (*(*)))malloc((__pyx_v_nfields * (sizeof(char (*))))));

  /* "src/hdf5Extension.pyx":507 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_nfields; ++__pyx_v_i) {

    /* "src/hdf5Extension.pyx":509 */
    (__pyx_v_field_names[__pyx_v_i]) = ((char (*))malloc((MAX_CHARS * (sizeof(char )))));
    __pyx_L4:;
  }
  __pyx_L5:;

  /* "src/hdf5Extension.pyx":511 */
  __pyx_v_ret = H5TBget_field_info(((struct __pyx_obj_Table *)__pyx_v_self)->group_id,((struct __pyx_obj_Table *)__pyx_v_self)->tablename,__pyx_v_field_names,__pyx_v_field_sizes,((struct __pyx_obj_Table *)__pyx_v_self)->field_offset,(&__pyx_v_rowsize));

  /* "src/hdf5Extension.pyx":514 */
  __pyx_1 = (__pyx_v_ret < 0);
  if (__pyx_1) {

    /* "src/hdf5Extension.pyx":515 */
    __pyx_4 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_4) {__pyx_lineno = 515; goto __pyx_L1;}
    __pyx_2 = PyString_FromString(__pyx_k37); if (!__pyx_2) {__pyx_lineno = 515; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_lineno = 515; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
    __pyx_2 = 0;
    __pyx_5 = PyObject_CallObject(__pyx_4, __pyx_3); if (!__pyx_5) {__pyx_lineno = 515; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_lineno = 515; goto __pyx_L1;}
    goto __pyx_L6;
  }
  __pyx_L6:;

  /* "src/hdf5Extension.pyx":516 */
  __pyx_v_ret = getfieldfmt(((struct __pyx_obj_Table *)__pyx_v_self)->group_id,((struct __pyx_obj_Table *)__pyx_v_self)->tablename,__pyx_v_fmt);

  /* "src/hdf5Extension.pyx":517 */
  __pyx_1 = (__pyx_v_ret < 0);
  if (__pyx_1) {

    /* "src/hdf5Extension.pyx":518 */
    __pyx_2 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_2) {__pyx_lineno = 518; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(__pyx_k38); if (!__pyx_3) {__pyx_lineno = 518; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_lineno = 518; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_5 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_5) {__pyx_lineno = 518; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_lineno = 518; goto __pyx_L1;}
    goto __pyx_L7;
  }
  __pyx_L7:;

  /* "src/hdf5Extension.pyx":520 */
  ((struct __pyx_obj_Table *)__pyx_v_self)->fmt = __pyx_v_fmt;

  /* "src/hdf5Extension.pyx":523 */
  __pyx_3 = createNamesTuple(__pyx_v_field_names,__pyx_v_nfields); if (!__pyx_3) {__pyx_lineno = 523; goto __pyx_L1;}
  Py_DECREF(__pyx_v_names_tuple);
  __pyx_v_names_tuple = __pyx_3;
  __pyx_3 = 0;

  /* "src/hdf5Extension.pyx":526 */
  __pyx_4 = PyInt_FromLong(__pyx_v_nrecords); if (!__pyx_4) {__pyx_lineno = 526; goto __pyx_L1;}
  __pyx_2 = PyString_FromString(__pyx_v_fmt); if (!__pyx_2) {__pyx_lineno = 526; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(3); if (!__pyx_5) {__pyx_lineno = 526; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_4);
  Py_INCREF(__pyx_v_names_tuple);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_v_names_tuple);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_2);
  __pyx_4 = 0;
  __pyx_2 = 0;
  __pyx_r = __pyx_5;
  __pyx_5 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("getTableInfo");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_read_buffer);
  Py_DECREF(__pyx_v_names_tuple);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static char (__pyx_k39[]) = "Problems reading records.";

static PyObject *__pyx_f_5Table_read_records(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5Table_read_records(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  long long __pyx_v_start;
  long long __pyx_v_nrecords;
  PyStringObject *__pyx_v_buffer = 0;
  int __pyx_v_ret;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"start","nrecords","buffer",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "LLO", __pyx_argnames, &__pyx_v_start, &__pyx_v_nrecords, &__pyx_v_buffer)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_buffer);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_buffer), &PyString_Type, "buffer")) {__pyx_lineno = 529; goto __pyx_L1;}

  /* "src/hdf5Extension.pyx":530 */

  /* "src/hdf5Extension.pyx":533 */
  __pyx_1 = ((__pyx_v_start + __pyx_v_nrecords) > ((struct __pyx_obj_Table *)__pyx_v_self)->totalrecords);
  if (__pyx_1) {

    /* "src/hdf5Extension.pyx":534 */
    __pyx_v_nrecords = (((struct __pyx_obj_Table *)__pyx_v_self)->totalrecords - __pyx_v_start);
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "src/hdf5Extension.pyx":537 */
  __pyx_v_ret = H5TBread_records(((struct __pyx_obj_Table *)__pyx_v_self)->group_id,((struct __pyx_obj_Table *)__pyx_v_self)->tablename,__pyx_v_start,__pyx_v_nrecords,((struct __pyx_obj_Table *)__pyx_v_self)->dst_size,((struct __pyx_obj_Table *)__pyx_v_self)->field_offset,((void (*))((PyStringObject *)((PyObject *)__pyx_v_buffer))->ob_sval));

  /* "src/hdf5Extension.pyx":540 */
  __pyx_1 = (__pyx_v_ret < 0);
  if (__pyx_1) {

    /* "src/hdf5Extension.pyx":541 */
    __pyx_2 = __Pyx_GetName(__pyx_b, "RuntimeError"); if (!__pyx_2) {__pyx_lineno = 541; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(__pyx_k39); if (!__pyx_3) {__pyx_lineno = 541; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_lineno = 541; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_5 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_5) {__pyx_lineno = 541; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_lineno = 541; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "src/hdf5Extension.pyx":543 */
  __pyx_3 = PyInt_FromLong(__pyx_v_nrecords); if (!__pyx_3) {__pyx_lineno = 543; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("read_records");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_buffer);
  return __pyx_r;
}

static PyObject *__pyx_tp_new_File(struct _typeobject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_File *p = (struct __pyx_obj_File *)o;
  if (__pyx_f_4File___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_File(PyObject *o) {
  struct __pyx_obj_File *p = (struct __pyx_obj_File *)o;
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_4File___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_File(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_File *p = (struct __pyx_obj_File *)o;
  return 0;
}

static int __pyx_tp_clear_File(PyObject *o) {
  struct __pyx_obj_File *p = (struct __pyx_obj_File *)o;
  return 0;
}

static struct PyMethodDef __pyx_methods_File[] = {
  {"getFileId", (PyCFunction)__pyx_f_4File_getFileId, METH_VARARGS|METH_KEYWORDS, 0},
  {"closeFile", (PyCFunction)__pyx_f_4File_closeFile, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_File = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_File = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_File = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_File = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_File = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "hdf5Extension.File", /*tp_name*/
  sizeof(struct __pyx_obj_File), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_File, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_File, /*tp_as_number*/
  &__pyx_tp_as_sequence_File, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_File, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_File, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_File, /*tp_traverse*/
  __pyx_tp_clear_File, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_File, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_File, /*tp_new*/
  _PyObject_Del, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_Group(struct _typeobject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_Group *p = (struct __pyx_obj_Group *)o;
  if (__pyx_f_5Group___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_Group(PyObject *o) {
  struct __pyx_obj_Group *p = (struct __pyx_obj_Group *)o;
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_5Group___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_Group(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_Group *p = (struct __pyx_obj_Group *)o;
  return 0;
}

static int __pyx_tp_clear_Group(PyObject *o) {
  struct __pyx_obj_Group *p = (struct __pyx_obj_Group *)o;
  return 0;
}

static struct PyMethodDef __pyx_methods_Group[] = {
  {"_f_createGroup", (PyCFunction)__pyx_f_5Group__f_createGroup, METH_VARARGS|METH_KEYWORDS, 0},
  {"_f_openGroup", (PyCFunction)__pyx_f_5Group__f_openGroup, METH_VARARGS|METH_KEYWORDS, 0},
  {"_f_listGroup", (PyCFunction)__pyx_f_5Group__f_listGroup, METH_VARARGS|METH_KEYWORDS, 0},
  {"_f_getGroupId", (PyCFunction)__pyx_f_5Group__f_getGroupId, METH_VARARGS|METH_KEYWORDS, 0},
  {"_f_getGroupName", (PyCFunction)__pyx_f_5Group__f_getGroupName, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Group = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_Group = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Group = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Group = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_Group = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "hdf5Extension.Group", /*tp_name*/
  sizeof(struct __pyx_obj_Group), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_Group, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Group, /*tp_as_number*/
  &__pyx_tp_as_sequence_Group, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Group, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Group, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_Group, /*tp_traverse*/
  __pyx_tp_clear_Group, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_Group, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_Group, /*tp_new*/
  _PyObject_Del, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_Table(struct _typeobject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_Table *p = (struct __pyx_obj_Table *)o;
  if (__pyx_f_5Table___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_Table(PyObject *o) {
  struct __pyx_obj_Table *p = (struct __pyx_obj_Table *)o;
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_Table(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_Table *p = (struct __pyx_obj_Table *)o;
  return 0;
}

static int __pyx_tp_clear_Table(PyObject *o) {
  struct __pyx_obj_Table *p = (struct __pyx_obj_Table *)o;
  return 0;
}

static struct PyMethodDef __pyx_methods_Table[] = {
  {"openTable", (PyCFunction)__pyx_f_5Table_openTable, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5Table_openTable},
  {"closeTable", (PyCFunction)__pyx_f_5Table_closeTable, METH_VARARGS|METH_KEYWORDS, 0},
  {"createTable", (PyCFunction)__pyx_f_5Table_createTable, METH_VARARGS|METH_KEYWORDS, 0},
  {"append_record", (PyCFunction)__pyx_f_5Table_append_record, METH_VARARGS|METH_KEYWORDS, 0},
  {"append_records", (PyCFunction)__pyx_f_5Table_append_records, METH_VARARGS|METH_KEYWORDS, 0},
  {"getTableTitle", (PyCFunction)__pyx_f_5Table_getTableTitle, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5Table_getTableTitle},
  {"getTableInfo", (PyCFunction)__pyx_f_5Table_getTableInfo, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5Table_getTableInfo},
  {"read_records", (PyCFunction)__pyx_f_5Table_read_records, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Table = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_Table = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Table = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Table = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_Table = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "hdf5Extension.Table", /*tp_name*/
  sizeof(struct __pyx_obj_Table), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_Table, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Table, /*tp_as_number*/
  &__pyx_tp_as_sequence_Table, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Table, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Table, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_Table, /*tp_traverse*/
  __pyx_tp_clear_Table, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_Table, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_Table, /*tp_new*/
  _PyObject_Del, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"isHDF5", (PyCFunction)__pyx_f_isHDF5, METH_VARARGS|METH_KEYWORDS, 0},
  {"getHDF5Version", (PyCFunction)__pyx_f_getHDF5Version, METH_VARARGS|METH_KEYWORDS, __pyx_doc_getHDF5Version},
  {"getExtCVSVersion", (PyCFunction)__pyx_f_getExtCVSVersion, METH_VARARGS|METH_KEYWORDS, __pyx_doc_getExtCVSVersion},
  {"getTablesVersion", (PyCFunction)__pyx_f_getTablesVersion, METH_VARARGS|METH_KEYWORDS, __pyx_doc_getTablesVersion},
  {0, 0, 0, 0}
};

static char (__pyx_k1[]) = "$Id: hdf5Extension.c,v 1.2 2002/10/04 20:13:44 falted Exp $";
static char (__pyx_k2[]) = "os.path";

DL_EXPORT(void) inithdf5Extension(void); /*proto*/
DL_EXPORT(void) inithdf5Extension(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  __pyx_m = Py_InitModule4("hdf5Extension", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  __pyx_b = PyImport_AddModule("__builtin__");
  PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b);
  if (PyType_Ready(&__pyx_type_File) < 0) {__pyx_lineno = 7; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "File", (PyObject *)&__pyx_type_File) < 0) {__pyx_lineno = 7; goto __pyx_L1;}
  if (PyType_Ready(&__pyx_type_Group) < 0) {__pyx_lineno = 7; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Group", (PyObject *)&__pyx_type_Group) < 0) {__pyx_lineno = 7; goto __pyx_L1;}
  if (PyType_Ready(&__pyx_type_Table) < 0) {__pyx_lineno = 7; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Table", (PyObject *)&__pyx_type_Table) < 0) {__pyx_lineno = 7; goto __pyx_L1;}

  /* "src/hdf5Extension.pyx":7 */
  __pyx_1 = PyString_FromString(__pyx_k1); if (!__pyx_1) {__pyx_lineno = 7; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "cvsid", __pyx_1) < 0) {__pyx_lineno = 7; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "src/hdf5Extension.pyx":14 */

  /* "src/hdf5Extension.pyx":14 */
  __pyx_1 = PyString_FromString(__pyx_k2); if (!__pyx_1) {__pyx_lineno = 14; goto __pyx_L1;}
  __pyx_2 = __Pyx_Import(__pyx_1, 0); if (!__pyx_2) {__pyx_lineno = 14; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_SetAttrString(__pyx_m, "os", __pyx_2) < 0) {__pyx_lineno = 14; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "src/hdf5Extension.pyx":17 */

  /* "src/hdf5Extension.pyx":22 */

  /* "src/hdf5Extension.pyx":27 */

  /* "src/hdf5Extension.pyx":35 */

  /* "src/hdf5Extension.pyx":59 */

  /* "src/hdf5Extension.pyx":85 */

  /* "src/hdf5Extension.pyx":115 */

  /* "src/hdf5Extension.pyx":134 */

  /* "src/hdf5Extension.pyx":138 */

  /* "src/hdf5Extension.pyx":141 */

  /* "src/hdf5Extension.pyx":172 */

  /* "src/hdf5Extension.pyx":179 */

  /* "src/hdf5Extension.pyx":183 */

  /* "src/hdf5Extension.pyx":190 */

  /* "src/hdf5Extension.pyx":193 */

  /* "src/hdf5Extension.pyx":206 */

  /* "src/hdf5Extension.pyx":217 */

  /* "src/hdf5Extension.pyx":222 */

  /* "src/hdf5Extension.pyx":223 */

  /* "src/hdf5Extension.pyx":224 */

  /* "src/hdf5Extension.pyx":226 */

  /* "src/hdf5Extension.pyx":257 */

  /* "src/hdf5Extension.pyx":260 */

  /* "src/hdf5Extension.pyx":265 */

  /* "src/hdf5Extension.pyx":275 */

  /* "src/hdf5Extension.pyx":276 */

  /* "src/hdf5Extension.pyx":277 */

  /* "src/hdf5Extension.pyx":279 */

  /* "src/hdf5Extension.pyx":284 */

  /* "src/hdf5Extension.pyx":295 */

  /* "src/hdf5Extension.pyx":306 */

  /* "src/hdf5Extension.pyx":310 */

  /* "src/hdf5Extension.pyx":313 */

  /* "src/hdf5Extension.pyx":316 */

  /* "src/hdf5Extension.pyx":331 */

  /* "src/hdf5Extension.pyx":334 */

  /* "src/hdf5Extension.pyx":335 */

  /* "src/hdf5Extension.pyx":336 */

  /* "src/hdf5Extension.pyx":337 */

  /* "src/hdf5Extension.pyx":338 */

  /* "src/hdf5Extension.pyx":339 */

  /* "src/hdf5Extension.pyx":340 */

  /* "src/hdf5Extension.pyx":341 */

  /* "src/hdf5Extension.pyx":342 */

  /* "src/hdf5Extension.pyx":343 */

  /* "src/hdf5Extension.pyx":345 */

  /* "src/hdf5Extension.pyx":357 */

  /* "src/hdf5Extension.pyx":371 */

  /* "src/hdf5Extension.pyx":379 */

  /* "src/hdf5Extension.pyx":441 */

  /* "src/hdf5Extension.pyx":454 */

  /* "src/hdf5Extension.pyx":466 */

  /* "src/hdf5Extension.pyx":470 */

  /* "src/hdf5Extension.pyx":528 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("hdf5Extension");
}

/* Runtime support code */

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
  PyObject *py_srcfile = 0;
  PyObject *py_funcname = 0;
  PyObject *py_globals = 0;
  PyObject *empty_tuple = 0;
  PyObject *empty_string = 0;
  PyCodeObject *py_code = 0;
  PyFrameObject *py_frame = 0;
  
  py_srcfile = PyString_FromString(__pyx_srcfile);
  if (!py_srcfile) goto bad;
  py_funcname = PyString_FromString(funcname);
  if (!py_funcname) goto bad;
  py_globals = PyModule_GetDict(__pyx_m);
  if (!py_globals) goto bad;
  empty_tuple = PyTuple_New(0);
  if (!empty_tuple) goto bad;
  empty_string = PyString_FromString("");
  if (!empty_string) goto bad;
  py_code = PyCode_New(
    0,            /*int argcount,*/
    0,            /*int nlocals,*/
    0,            /*int stacksize,*/
    0,            /*int flags,*/
    empty_string, /*PyObject *code,*/
    empty_tuple,  /*PyObject *consts,*/
    empty_tuple,  /*PyObject *names,*/
    empty_tuple,  /*PyObject *varnames,*/
    empty_tuple,  /*PyObject *freevars,*/
    empty_tuple,  /*PyObject *cellvars,*/
    py_srcfile,   /*PyObject *filename,*/
    py_funcname,  /*PyObject *name,*/
    __pyx_lineno,   /*int firstlineno,*/
    empty_string  /*PyObject *lnotab*/
  );
  if (!py_code) goto bad;
  py_frame = PyFrame_New(
    PyThreadState_Get(), /*PyThreadState *tstate,*/
    py_code,             /*PyCodeObject *code,*/
    py_globals,          /*PyObject *globals,*/
    0                    /*PyObject *locals*/
  );
  if (!py_frame) goto bad;
  py_frame->f_lineno = __pyx_lineno;
  PyTraceBack_Here(py_frame);
bad:
  Py_XDECREF(py_srcfile);
  Py_XDECREF(py_funcname);
  Py_XDECREF(empty_tuple);
  Py_XDECREF(empty_string);
  Py_XDECREF(py_code);
  Py_XDECREF(py_frame);
}

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, char *name) {
  if (PyObject_TypeCheck(obj, type))
    return 1;
  PyErr_Format(PyExc_TypeError,
    "Argument '%s' has incorrect type (expected %s, got %s)",
    name, type->tp_name, obj->ob_type->tp_name);
  return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
  PyObject *__import__ = 0;
  PyObject *empty_list = 0;
  PyObject *module = 0;
  PyObject *global_dict = 0;
  PyObject *empty_dict = 0;
  PyObject *list;
  __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
  if (!__import__)
    goto bad;
  if (from_list)
    list = from_list;
  else {
    empty_list = PyList_New(0);
    if (!empty_list)
      goto bad;
    list = empty_list;
  }
  global_dict = PyModule_GetDict(__pyx_m);
  if (!global_dict)
    goto bad;
  empty_dict = PyDict_New();
  if (!empty_dict)
    goto bad;
  module = PyObject_CallFunction(__import__, "OOOO",
    name, global_dict, empty_dict, list);
bad:
  Py_XDECREF(empty_list);
  Py_XDECREF(__import__);
  Py_XDECREF(empty_dict);
  return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, char *name) {
  PyObject *result;
  result = PyObject_GetAttrString(dict, name);
  if (!result)
    PyErr_SetString(PyExc_NameError, name);
  return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
  Py_XINCREF(type);
  Py_XINCREF(value);
  Py_XINCREF(tb);
  /* First, check the traceback argument, replacing None with NULL. */
  if (tb == Py_None) {
    Py_DECREF(tb);
    tb = 0;
  }
  else if (tb != NULL && !PyTraceBack_Check(tb)) {
    PyErr_SetString(PyExc_TypeError,
      "raise: arg 3 must be a traceback or None");
    goto raise_error;
  }
  /* Next, replace a missing value with None */
  if (value == NULL) {
    value = Py_None;
    Py_INCREF(value);
  }
  /* Next, repeatedly, replace a tuple exception with its first item */
  while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
    PyObject *tmp = type;
    type = PyTuple_GET_ITEM(type, 0);
    Py_INCREF(type);
    Py_DECREF(tmp);
  }
  if (PyString_Check(type))
    ;
  else if (PyClass_Check(type))
    ; /*PyErr_NormalizeException(&type, &value, &tb);*/
  else if (PyInstance_Check(type)) {
    /* Raising an instance.  The value should be a dummy. */
    if (value != Py_None) {
      PyErr_SetString(PyExc_TypeError,
        "instance exception may not have a separate value");
      goto raise_error;
    }
    else {
      /* Normalize to raise <class>, <instance> */
      Py_DECREF(value);
      value = type;
      type = (PyObject*) ((PyInstanceObject*)type)->in_class;
      Py_INCREF(type);
    }
  }
  else {
    /* Not something you can raise.  You get an exception
       anyway, just not what you specified :-) */
    PyErr_Format(PyExc_TypeError,
           "exceptions must be strings, classes, or "
           "instances, not %s", type->ob_type->tp_name);
    goto raise_error;
  }
  PyErr_Restore(type, value, tb);
  return;
raise_error:
  Py_XDECREF(value);
  Py_XDECREF(type);
  Py_XDECREF(tb);
  return;
}

static PyObject *__Pyx_GetStdout(void) {
  PyObject *f = PySys_GetObject("stdout");
  if (!f) {
    PyErr_SetString(PyExc_RuntimeError, "lost sys.stdout");
  }
  return f;
}

static int __Pyx_PrintItem(PyObject *v) {
  PyObject *f;
  
  if (!(f = __Pyx_GetStdout()))
    return -1;
  if (PyFile_SoftSpace(f, 1)) {
    if (PyFile_WriteString(" ", f) < 0)
      return -1;
  }
  if (PyFile_WriteObject(v, f, Py_PRINT_RAW) < 0)
    return -1;
  if (PyString_Check(v)) {
    char *s = PyString_AsString(v);
    int len = PyString_Size(v);
    if (len > 0 &&
      isspace(Py_CHARMASK(s[len-1])) &&
      s[len-1] != ' ')
        PyFile_SoftSpace(f, 0);
  }
  return 0;
}

static int __Pyx_PrintNewline(void) {
  PyObject *f;
  
  if (!(f = __Pyx_GetStdout()))
    return -1;
  if (PyFile_WriteString("\n", f) < 0)
    return -1;
  PyFile_SoftSpace(f, 0);
  return 0;
}

static void __Pyx_WriteUnraisable(char *name) {
  PyObject *old_exc, *old_val, *old_tb;
  PyObject *ctx;
  PyErr_Fetch(&old_exc, &old_val, &old_tb);
  ctx = PyString_FromString(name);
  PyErr_Restore(old_exc, old_val, old_tb);
  if (!ctx)
    ctx = Py_None;
  PyErr_WriteUnraisable(ctx);
}
